image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - init: |
      python3 -m pip install -r requirements.txt
    command: |
      gp open pipelines.py
      echo
      echo "Running 'python3 pipelines.py' demo!"
      python3 pipelines.py

